public class RV_SHT_Calculation_CONSTANTS {
   public final String CONST_CHF_TO_USD='EUR/CHF';
    public final String CONST_EU_TO_USD='EUR/USD';
    public final String CONST_USD1_CURRENCY_UNIT='US';
    public final String CONST_USD2_CURRENCY_UNIT='USD';    
    public final String CONST_CH1_CURRENCY_UNIT='CH';
    public final String CONST_CH2_CURRENCY_UNIT='CHF'; 
    public final String CONST_CH_CURRENCY_UNIT='CH';
    public final String CONST_US_CURRENCY_UNIT='EU'; 
    public final String CONST_DELIMETER_GRADE_META='_';
    public final String CONST_MOGAS_VPR_Cargo='ULG100 VP_Cargo';
    public final String CONST_MOGAS_98_Cargo='ULG98_Cargo';
    public final String  CONST_MOGAS_VPR_Barge='ULG100 VP_Barge';   
    public final String CONST_PRODUCT_MOGAS='MOGAS';
    public final String CONST_TYPE_THIRD_PARTY='Third party';
    public final String CONST_TYPE_SHELL_OWNED='Own supply';     
    public final String CONST_ALT1_TYPE='Alternate1'; 
    public final String CONST_ALT2_TYPE='Alternate2';
    public final String CONST_BARGE='Barge';
    public final String CONST_CARGO='Cargo';
    
    
}