public class SaveFromSAP extends DataSource.AsyncSaveCallback {
/*
    override public void processSave(Database.SaveResult saveResult){
        
        if(saveResult.isSuccess())
        {
            system.debug('The save was successful with: '+saveResult);
            system.debug('Record Id: '+ saveResult.getId());
            system.debug('Id: '+ saveResult.id);
            
        }
        else if(!saveResult.isSuccess())
        {
            system.debug('The save was unsuccessful with: '+saveResult);
        }
    }
*/
    
}