public class TCP_STNSAPSoldToShipToWrapper {
    
    @AuraEnabled public String SOLDTO {get; set;}
    @AuraEnabled public String SALESORG {get; set;}
    @AuraEnabled public String DISTCHNL {get; set;}
    @AuraEnabled public String DIVISION {get; set;}
    @AuraEnabled public String FULLLOAD {get; set;}
    @AuraEnabled public String PARTNERNO {get; set;}
    @AuraEnabled public String PARTNERFUNC {get; set;}
    @AuraEnabled public String PARTNERCNT {get; set;}    
    @AuraEnabled public String NAME {get; set;}
    @AuraEnabled public String STREET {get; set;}
    @AuraEnabled public String CITY {get; set;}
    @AuraEnabled public String COUNTRY {get; set;}
    @AuraEnabled public String POSTCODE {get; set;}
    @AuraEnabled public String BILLINGBLK {get; set;}
    @AuraEnabled public String DELIVERYBLK {get; set;}
    @AuraEnabled public String ORDERBLK {get; set;}    
    @AuraEnabled public String INCO1 {get; set;}
    @AuraEnabled public String INCO2 {get; set;}
    @AuraEnabled public String SHIP_COND {get; set;}
    @AuraEnabled public String STATUS {get; set;}


}