public with sharing class TCP_Constants {
    
public static final string ORD_BY_CREATEDDATE = ' order by CreatedDate desc';   
public static final string CREATEDDATE_LASTNDAYS=' and createddate=LAST_N_DAYS:';
public static final string HEARDERCNTLR_DMLEXP='This is a constructed exception for testing and code coverage';
public static final string NO_CHANGE='No Change';
public static final string MYCOMPANYUSERCNTLR_EXPMSG='My Company Users or Contact Us Expection';
public static final string ERROR_MESSAGE='Message ';
}