public class TCP_GSAPFileWrapper {
    @AuraEnabled public String Document {get; set;}
    @AuraEnabled public String Outputtype {get; set;}
    @AuraEnabled public String Outputdesc {get; set;}
    @AuraEnabled public String Filenetid {get; set;}
    @AuraEnabled public String Reserve {get; set;}
    @AuraEnabled public String Application {get; set;}
    @AuraEnabled public String Coa {get; set;}
    @AuraEnabled public String Uri {get; set;}
    @AuraEnabled public String Zsectyp {get; set;}
    
}