name: Validate metadata

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [sandbox/DACHDev,sandbox/RevLiteDev,sandbox/BETDev,sandbox/TCPDev,sandbox/HotFixDev,sandbox/BAUDev,sandbox/RevQA,sandbox/BAUQA,sandbox/BETQA,sandbox/TCPQA,sandbox/HotFixQA,sandbox/UAT,sandbox/Regression,sandbox/PSE,main]

jobs:
  ValidateOnDACHDev:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'sandbox/DACHDev'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.DACHDEV_USERNAME }}
      login_credentials: ${{ secrets.DACHDEV_AUTH_URL }}

  ValidateOnRevLiteDev:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'sandbox/RevLiteDev'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.REVLITEDEV_USERNAME }}
      login_credentials: ${{ secrets.REVLITEDEV_AUTH_URL }}

  ValidateOnBETDev:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'sandbox/BETDev'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.BETDEV_USERNAME }}
      login_credentials: ${{ secrets.BETDEV_AUTH_URL }}

  ValidateOnTCPDev:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'sandbox/TCPDev'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.TCPDEV_USERNAME }}
      login_credentials: ${{ secrets.TCPDEV_AUTH_URL }}

  ValidateOnHotFixDev:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'sandbox/HotFixDev'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.HOTFIXDEV_USERNAME }}
      login_credentials: ${{ secrets.HOTFIXDEV_AUTH_URL }}

  ValidateOnBAUDev:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'sandbox/BAUDev'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.BAUDEV_USERNAME }}
      login_credentials: ${{ secrets.BAUDEV_AUTH_URL }}

  ValidateOnRevQA:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'sandbox/RevQA'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.REVQA_USERNAME }}
      login_credentials: ${{ secrets.REVQA_AUTH_URL }}

  ValidateOnBAUQA:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'sandbox/BAUQA'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.BAUQA_USERNAME }}
      login_credentials: ${{ secrets.BAUQA_AUTH_URL }}

  ValidateOnBETQA:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'sandbox/BETQA'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.BETQA_USERNAME }}
      login_credentials: ${{ secrets.BETQA_AUTH_URL }}

  ValidateOnTCPQA:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'sandbox/TCPQA'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.TCPQA_USERNAME }}
      login_credentials: ${{ secrets.TCPQA_AUTH_URL }}

  ValidateOnHotFixQA:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'sandbox/HotFixQA'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.HOTFIXQA_USERNAME }}
      login_credentials: ${{ secrets.HOTFIXQA_AUTH_URL }}

  ValidateOnUAT:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'sandbox/UAT'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.UAT_USERNAME }}
      login_credentials: ${{ secrets.UAT_AUTH_URL }}

  ValidateOnRegression:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'sandbox/Regression'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.REGRESSION_USERNAME }}
      login_credentials: ${{ secrets.REGRESSION_AUTH_URL }}

  ValidateOnPSE:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'sandbox/PSE'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.PSE_USERNAME }}
      login_credentials: ${{ secrets.PSE_AUTH_URL }}

  ValidateOnProduction:
    uses: sede-x/sf-STASCO/.github/workflows/ValidateAction.yml@main
    if: github.base_ref == 'main'
    with:
      test_level_run: RunLocalTests
    secrets:
      default_username: ${{ secrets.PROD_USERNAME }}
      login_credentials: ${{ secrets.PROD_AUTH_URL }}